image:
  repository: alpine
  tag: latest
  pullPolicy: IfNotPresent

keycloak:
  url: "https://keycloak.example.local/auth"
  username: "admin"
  password: "admin"
  realm: "master"
  clientId: "clientid1"
  clientName: "oauth-client-2"
  redirectUris:
    - https://app.example.com/oidc
    - wire://e2ei/oauth2redirect
  webOrigins:
    - https://app.example.com
